#- name: Update the repository cache and update package "nginx" to latest version using default release squeeze-backport
#  ansible.builtin.apt:
#    name: nginx
#    state: latest
#    default_release: squeeze-backports
#    update_cache: yes

- name: Install the newest version of package "nginx"
  ansible.builtin.apt:
    name: nginx
    state: present

- name: Copy files/default to /etc/nginx/sites-enabled/default on remote virtual machine
  ansible.builtin.copy:
  when: inventory_hostname == webservers[0]
    src: files/default
    dest: /etc/nginx/sites-enabled/default
  notify: "restart nginx service"


- name: Copy files/default to /etc/nginx/sites-enabled/default on remote virtual machine
  when: inventory_hostname == webservers[1]
  ansible.builtin.template:
    src: templates/default.j2
    dest: /etc/nginx/sites-enabled/default
  notify: "restart nginx service"

- name: start nginx service
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true

- name: Restart nginx
  service:
    name: nginx
    state: restarted
