- name: Prometheus influxdb exporter
  get_url:
    url: https://github.com/carlpett/influxdb_stats_exporter/releases/download/v0.1.1/influx_stats_exporter_linux_amd64
    dest: /usr/local/bin/influx_stats_exporter_linux_amd64
    mode: 0555

- name: Copy service template
  template:
    src: influxdb-stats-exporter.service.j2
    dest: /etc/systemd/system/prometheus-influxdb-stats-exporter.service
  notify:
    - reload daemon
    - restart influxdb exporter

- name: Influxdb Exporter
  service:
    name: prometheus-influxdb-stats-exporter
    state: started
    enabled: yes
