- name: Install haproxy and haproxy exporter
  apt: 
    name: 
      - haproxy


- name: Copy HAproxy conf file
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - { src: "haproxy.conf.j2", dest: "/etc/haproxy/haproxy.cfg" }
    - { src: "haproxy.scrape-uri.j2", dest: "/etc/default/prometheus-haproxy-exporter" }
  notify:
    - restart haproxy


- name: Start HAproxy on boot
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
    - haproxy
