- name: Download packages
  get_url:
    url: "{{ item.url }}"
    dest: "{{ item.dest }}"
  loop:
    - { url: "https://dl.influxdata.com/influxdb/releases/influxdb_1.8.10_amd64.deb", dest: 
"/opt/influxdb_1.8.10_amd64.deb" }
    - { url: "https://dl.influxdata.com/telegraf/releases/telegraf_1.28.2-1_amd64.deb", dest: 
"/opt/telegraf_1.28.2-1_amd64.deb" }

- name: Install packages
  ansible.builtin.apt:
    deb: "{{ item.deb }}"
  loop:
    - { deb: "/opt/influxdb_1.8.10_amd64.deb" }
    - { deb: "/opt/telegraf_1.28.2-1_amd64.deb" }
  
- name: Reconfigure telegraf & influxdb
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - { src: "telegraf.conf.j2", dest: "/etc/telegraf/telegraf.conf" }
    - { src: "influxdb.conf.j2", dest: "/etc/influxdb/influxdb.conf" }
  notify: "restart telegraf"
  
- name: Start and enable services
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: true
  loop:
    - influxdb
    - telegraf

- name: influxdb backup directory
  ansible.builtin.file:
    path: /home/backup/influxdb
    state: directory
    owner: backup
    group: backup
    mode: 0700

- name: influxdb backup cronjob
  template:
    src: influxdb_backup.j2
    dest: /etc/cron.d/influxdb-backup
