- name: Give insecure permissions to an existing file
  ansible.builtin.file:
    path: /etc/apt/keyrings/
    state: directory

- name: Add Example GPG key
  ansible.builtin.apt_key:
    url: https://apt.grafana.com/gpg.key
    state: present

- name: Add grafana repository into sources list using specified filename
  ansible.builtin.apt_repository:
    repo: "deb https://packages.grafana.com/oss/deb stable main"
    state: present

- name: Install the newest version of package "grafana"
  ansible.builtin.apt:
    name: grafana
    state: present

- name: Copy file grafana.ini.j2 to /etc/grafana/grafana.ini
  ansible.builtin.template:
    src: grafana.ini.j2
    dest: /etc/grafana/grafana.ini
  notify: "restart grafana"

- name: Start Grafana
  ansible.builtin.service:
    name: grafana-server
    state: started
    enabled: yes

- name: Create a directory for dashboards
  ansible.builtin.file:
    path: /var/lib/grafana/dashboards
    state: directory

- name: Copy main.json to /var/lib/grafana/dashboards
  ansible.builtin.copy:
    src: main2.json
    dest: /var/lib/grafana/dashboards/main.json

- name: Copy file datasource.yaml.j2 to datasources of grafana
  ansible.builtin.copy:
    src: datasource.yaml
    dest: /etc/grafana/provisioning/datasources/datasource.yaml
  notify: "restart grafana"

- name: Copy file dashboards.yaml.j2 to dasboards of grafana
  ansible.builtin.copy:
    src: dashboards.yaml
    dest: /etc/grafana/provisioning/dashboards/main.yaml
  notify: "restart grafana"

