- name: Install the package sqlalchemy
  ansible.builtin.apt:
    name: uwsgi
    state: present

- name: Install the package sqlalchemy
  ansible.builtin.apt:
    name: uwsgi-plugin-python3
    state: present

- name: Copy file with owner and permissions
  ansible.builtin.copy:
    src: files/agama.ini
    dest: /etc/uwsgi/apps-enabled/agama.ini
    notify: "restart uwsgi service"
