- name: Install the uwsgi
  ansible.builtin.apt:
    name: uwsgi
    state: present

- name: Install the package uwsgi-plugin-python3
  ansible.builtin.apt:
    name: 
      - uwsgi-plugin-python3
    state: present

- name: Copy file with owner and permission of agama.ini
  ansible.builtin.template:
    src: agama.ini.j2
    dest: /etc/uwsgi/apps-enabled/agama.ini
    owner: agama
    mode: 0600
  no_log: true  
  notify: "restart uwsgi service"

- name: start uWSGI service
  ansible.builtin.service:
    name: uwsgi
    state: started
    enabled: true

- name: Restart uwsgi
  service:
    name: uwsgi
    state: restarted
