{
 "title": "Basic system",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "node load",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_load1", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Used memory in %",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node CPU seconds total",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by (instance, cpu) (irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Filesystem usage in %",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes - node_filesystem_free_bytes) / node_filesystem_size_bytes * 100",
     "legendFormat": "{{instance}} - {{fstype}}"
    }
   ]
  },
  {
   "title": "Disk I/O in seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "rate(node_disk_io_time_seconds_total[5m])",
     "legendFormat": "{{instance}} - {{device}}"
    }
   ]
  },
  {
   "title": "Transmited bytes",
   "type": "stat",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total[5m])",
     "legendFormat": "{{instance}}{{device}}"
    }
   ]
  },
  {
   "title": "Recieved bytes",
   "type": "stat",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total[5m])",
     "legendFormat": "{{instance}}: {{device}}"
    }
   ]
  }
 ]
}