{
 "title": "Bind",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Bind9 status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bind_up{job=\"bind_exporter\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "MichalKaiser-1 sending notifies",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "syslog",
     "query": "SELECT mean(\"value\") FROM \"syslog\"WHERE (\"appname\"::tag = 'named' AND \"message\"::field =~ /sending notifies/)",
     "select": [
      [
       { "params": [ "message" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "appname::tag", "operator": "=", "value": "named" },
      { "condition": "AND", "key": "message::field", "operator": "=~", "value": "/sending notifies/" },
      { "condition": "AND", "key": "hostname::tag", "operator": "=", "value": "MichalKaiser-1" }
     ]
    }
   ]
  },
  {
   "title": "MichalKaiser-1 sending notifies",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "syslog",
     "query": "SELECT mean(\"value\") FROM \"syslog\"WHERE (\"appname\"::tag = 'named' AND \"message\"::field =~ /sending notifies/)",
     "select": [
      [
       { "params": [ "message" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "appname::tag", "operator": "=", "value": "named" },
      { "condition": "AND", "key": "message::field", "operator": "=~", "value": "/sending notifies/" },
      { "condition": "AND", "key": "hostname::tag", "operator": "=", "value": "MichalKaiser-1" }
     ]
    }
   ]
  },
  {
   "title": "MichalKaiser-3 sending notifies",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "syslog",
     "query": "SELECT mean(\"value\") FROM \"syslog\"WHERE (\"appname\"::tag = 'named' AND \"message\"::field =~ /sending notifies/)",
     "select": [
      [
       { "params": [ "message" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "appname::tag", "operator": "=", "value": "named" },
      { "condition": "AND", "key": "message::field", "operator": "=~", "value": "/sending notifies/" },
      { "condition": "AND", "key": "hostname::tag", "operator": "=", "value": "MichalKaiser-3" }
     ]
    }
   ]
  },
  {
   "title": "MichalKaiser-1 recieved notify",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "syslog",
     "query": "SELECT mean(\"value\") FROM \"syslog\"WHERE (\"appname\"::tag = 'named' AND \"message\"::field =~ /sending notifies/)",
     "select": [
      [
       { "params": [ "message" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "appname::tag", "operator": "=", "value": "named" },
      { "condition": "AND", "key": "message::field", "operator": "=~", "value": "/received notify/" },
      { "condition": "AND", "key": "hostname::tag", "operator": "=", "value": "MichalKaiser-1" }
     ]
    }
   ]
  },
  {
   "title": "MichalKaiser-2 recieved notify",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "syslog",
     "query": "SELECT mean(\"value\") FROM \"syslog\"WHERE (\"appname\"::tag = 'named' AND \"message\"::field =~ /sending notifies/)",
     "select": [
      [
       { "params": [ "message" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "appname::tag", "operator": "=", "value": "named" },
      { "condition": "AND", "key": "message::field", "operator": "=~", "value": "/received notify/" },
      { "condition": "AND", "key": "hostname::tag", "operator": "=", "value": "MichalKaiser-2" }
     ]
    }
   ]
  },
  {
   "title": "MichalKaiser-2 recieved notify",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "syslog",
     "query": "SELECT mean(\"value\") FROM \"syslog\"WHERE (\"appname\"::tag = 'named' AND \"message\"::field =~ /sending notifies/)",
     "select": [
      [
       { "params": [ "message" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "appname::tag", "operator": "=", "value": "named" },
      { "condition": "AND", "key": "message::field", "operator": "=~", "value": "/received notify/" },
      { "condition": "AND", "key": "hostname::tag", "operator": "=", "value": "MichalKaiser-3" }
     ]
    }
   ]
  },
  {
   "title": "Named syslog for recieved notfiy",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "hostname::tag" ], "type": "tag" }
     ],
     "measurement": "syslog",
     "select": [
      [
       { "params": [ "severity_code" ], "type": "field" }
      ],
      [
       { "params": [ "message" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "appname::tag", "operator": "=", "value": "named" },
      { "condition": "AND", "key": "message::field", "operator": "=~", "value": "/sending notifies/" }
     ]
    }
   ]
  },
  {
   "title": "Named syslog for recieved notfiy",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "hostname::tag" ], "type": "tag" }
     ],
     "measurement": "syslog",
     "select": [
      [
       { "params": [ "severity_code" ], "type": "field" }
      ],
      [
       { "params": [ "message" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "appname::tag", "operator": "=", "value": "named" },
      { "condition": "AND", "key": "message::field", "operator": "=~", "value": "/received notify/" }
     ]
    }
   ]
  },
  {
   "title": "Bind proccess cpu seconds total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "rate(bind_process_cpu_seconds_total[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Bind incoming queiries in total with type A",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "rate(bind_incoming_queries_total{type=\"A\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}