{
 "title": "main",
 "description": "hope you will work finally",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Bind status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bind_up{instance=\"michalkaiser-1:9119\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nginx michalkaiser-1",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nginx_up{instance=\"MichalKaiser-1:9113\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nginx michalkaiser-2",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nginx_up{instance=\"MichalKaiser-2:9113\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mysql status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_up{instance=\"michalkaiser-2:9104\", job=\"Mysql\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "influxd_exporter_stats_query_success",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(influxdb_exporter_stats_query_success{instance=\"michalkaiser-2:9424\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nginx servers active connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "targets": [
    { "expr": "nginx_connections_active", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Bind resolver total queries",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "bind_resolver_queries_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "MySQL global status commands total",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_global_status_commands_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU status michalkaiser-1",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(node_cpu_seconds_total{mode=\"idle\", instance=\"MichalKaiser-1:9100\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU status michalkaiser-2",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(node_cpu_seconds_total{mode=\"idle\", instance=\"MichalKaiser-2:9100\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory michalkaiser-2",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_memory_Active_bytes{instance=\"MichalKaiser-2:9100\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pinger for google.com and vutbr.cz",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "dst::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "rtt",
     "query": "SELECT mean(\"value\") FROM \"rtt\" WHERE $timeFilter GROUP BY time(1s) fill(null)",
     "select": [
      [
       { "params": [ "rtt" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "dst::tag", "operator": "=", "value": "vutbr.cz" },
      { "condition": "OR", "key": "dst::tag", "operator": "=", "value": "google.com" }
     ]
    }
   ]
  },
  {
   "title": "Pinger for ttu.ee and cloudfare.com",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "dst::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "rtt",
     "query": "SELECT mean(\"value\") FROM \"rtt\" WHERE $timeFilter GROUP BY time(1s) fill(null)",
     "select": [
      [
       { "params": [ "rtt" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "dst::tag", "operator": "=", "value": "cloudflare.com" },
      { "condition": "OR", "key": "dst::tag", "operator": "=", "value": "ttu.ee" }
     ]
    }
   ]
  },
  {
   "title": "Memory MichalKaiser-1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_memory_Active_bytes{instance=\"MichalKaiser-1:9100\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}