{
 "title": "main-new",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Memory consumption",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes{instance!=\"localhost:9100\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU load",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(node_cpu_seconds_total{mode=\"user\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " http Requests/minute ",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "rate(nginx_http_requests_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "InfluxDB write rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "influxdb_write_write_ok{instance=\"influxdb:9424\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "mysql selects/minute",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "rate(mysql_global_status_commands_total{command=\"select\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "dst::tag" ], "type": "tag" }
     ],
     "measurement": "rtt",
     "select": [
      [
       { "params": [ "rtt" ], "type": "field" },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ],
     "tags": [
      { "key": "dst::tag", "operator": "=", "value": "cloudflare.com" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "dst::tag" ], "type": "tag" }
     ],
     "measurement": "rtt",
     "select": [
      [
       { "params": [ "rtt" ], "type": "field" },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ],
     "tags": [
      { "key": "dst::tag", "operator": "=", "value": "google.com" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "dst::tag" ], "type": "tag" }
     ],
     "measurement": "rtt",
     "select": [
      [
       { "params": [ "rtt" ], "type": "field" },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ],
     "tags": [
      { "key": "dst::tag", "operator": "=", "value": "ttu.ee" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "dst::tag" ], "type": "tag" }
     ],
     "measurement": "rtt",
     "select": [
      [
       { "params": [ "rtt" ], "type": "field" },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ],
     "tags": [
      { "key": "dst::tag", "operator": "=", "value": "vutbr.cz" }
     ]
    }
   ]
  },
  {
   "title": "dns selects/minute",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "rate(bind_resolver_queries_total[1m])"
    }
   ]
  }
 ]
}