{
 "title": "MySQL",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "MySQL Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mysql_up", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "MySQL server ID",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_global_variables_server_id",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "MySQL server read-only status",
   "type": "stat",
   "description": "Master -> Read/Write\nReplica -> Read only",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_global_variables_read_only",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "MySQL replica IO thread",
   "type": "stat",
   "description": "IO thread on replication side that receives the changes that are sent from the master and writes it to a file",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_slave_status_slave_io_running",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "MySQL replica SQL thread",
   "type": "stat",
   "description": "SQL thread on replication side continuously reads the relay log and applies the changes to the replica server.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_slave_status_slave_sql_running",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}