{
 "title": "Nginx",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Nginx status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nginx_up", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Nginx connections waiting 24 h",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "changes(nginx_connections_waiting[24h])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Nginx connections accepted 24 h",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "changes(nginx_connections_accepted[24h])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Nginx connections handled 24 h",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "changes(nginx_connections_handled[24h])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total HTTP requests",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "rate(nginx_http_requests_total[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Nginx active connections",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "sum by(instance) (nginx_connections_active)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}