{
 "title": "Status",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "mysql status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_up{job=\"mysql_exporter\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Bind9 status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bind_up{job=\"bind_exporter\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Haproxy server status",
   "type": "stat",
   "gridPos": { "h": 11, "w": 11, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "haproxy_server_up{job=\"haproxy\"}",
     "legendFormat": "{{instance}}:{{server}}"
    }
   ]
  },
  {
   "title": "Keepalived state",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "keepalived_vrrp_state{job=\"keepalived\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Nginx status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 5, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nginx_up", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Haproxy status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "haproxy_up{job=\"haproxy\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "InfluxDB health",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 5, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "influxdb_exporter_stats_query_success{instance=\"influxdb:9424\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}