- name: Add the user agama
  ansible.builtin.user:
    name: agama
    comment: agama

- name: Change file ownership, group and permissions
  ansible.builtin.file:
    path: /opt/agama
    owner: agama
    state: directory

- name: Install the package sqlalchemy
  ansible.builtin.apt:
    name: 
      - python3-flask-sqlalchemy
      - python3-pymysql
    state: present

- name: Download agama.py
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/hudolejev/agama/master/agama.py
    dest: /opt/agama
