- name: Install MySQL Exporter
  ansible.builtin.apt:
    name: prometheus-mysqld-exporter
    state: present

- name: Create directory
  file:
  path: /var/lib/prometheus
  state: directory

- name: Copy .my.cnf template to /var/lib/prometheus/.my.cnf
  ansible.builtin.template:
    src: my.cnf.j2
    dest: /var/lib/prometheus/.my.cnf
  notify:
    - Daemon reload
    - restart mysql-exporter service

- name: Create MySQL Exporter user
  community.mysql.mysql_user:
    name: "{{ mysql_exporter_user }}"
    password: "{{ mysql_exporter_password }}"
    host: "%"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    priv: '*.*:PROCESS,REPLICATION CLIENT,SELECT'
  no_log: true

- name: Add prometheus-mysqld-exporter file to /etc/default/prometheus-mysqld-exporter
  ansible.builtin.template:
    src: prometheus-mysqld-exporter.j2
    dest: /etc/default/prometheus-mysqld-exporter
  notify: restart mysql-exporter service

- name: Force all notified handlers to run at this point, not waiting for normal sync points
  meta: flush_handlers

- name: Start MySQL exporter
  ansible.builtin.service:
    enabled: yes
    name: prometheus-mysqld-exporter
    state: started
