- name: Install the newest version of package "mysql-server"
  ansible.builtin.apt:
    name: mysql-server
    state: present

- name: start mysql service
  ansible.builtin.service:
    name: mysql
    state: started
    enabled: true

- name: Copy file override.cnf to /etc/mysql/mysql.conf.d/override.cnf
  ansible.builtin.copy:
    src: files/override.cnf
    dest: /etc/mysql/mysql.conf.d/override.cnf
  notify: "restart mysql service"

- name: Copy file my_mysql.cnf.j2 to /etc/mysql/my.cnf
  ansible.builtin.template:
    src: my_mysql.cnf.j2
    dest: /etc/mysql/my.cnf
  notify: "restart mysql service"

- name: Install the newest version of package "python3-pymysql"
  ansible.builtin.apt:
    name: python3-pymysql
    state: present

- name: MySQL database
  community.mysql.mysql_db:
    name: "{{ mysql_database }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock    

- name: MySQL user Agama
  community.mysql.mysql_user:
    name: "{{ mysql_user }}"
    password: "{{ mysql_password }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    host: "%"
    priv: "{{ mysql_database }}.*:ALL"

- name: mysql directory
  ansible.builtin.file:
    path: /home/backup/mysql
    state: directory
    owner: backup
    group: backup
    mode: '0775'

- name: MySql user for backup
  mysql_user:
    name: "{{mysql_user_backup}}"
    password: "{{mysql_backup_password}}"
    priv: '{{mysql_database}}.*:LOCK TABLES,SELECT'
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: cp my_mysql_backup.cnf.j2 to /home/backup/.my.cnf
  template:
    src: my_mysql_backup.cnf.j2
    dest: /home/backup/.my.cnf
    owner: backup
    group: backup
    force: yes
    mode: '0600'
  no_log: true

- name: Cronjob cp
  template:
    src: mysql-backup.j2
    dest: /etc/cron.d/mysql-backup
    force: yes
    mode: '0644'


# - name: MySQL user Exporter
#   community.mysql.mysql_user:
#     name: "{{ mysql_exporter_user }}"
#     password: "{{ mysql_exporter_password }}"
#     login_unix_socket: /var/run/mysqld/mysqld.sock
#     host: "%"
#     priv: "{{ mysql_database }}.*:SUPER"
#     state: present
