- name: Install the newest version of package "mysql-server"
  ansible.builtin.apt:
    name: mysql-server
    state: present

- name: start mysql service
  ansible.builtin.service:
    name: mysql
    state: started
    enabled: true

- name: Copy file override.cnf to /etc/mysql/mysql.conf.d/override.cnf
  ansible.builtin.copy:
    src: files/override.cnf
    dest: /etc/mysql/mysql.conf.d/override.cnf
  notify: "restart mysql service"

- name: Copy file my_mysql.cnf.j2 to /etc/mysql/my.cnf
  ansible.builtin.template:
    src: my_mysql.cnf.j2
    dest: /etc/mysql/my.cnf
  notify: "restart mysql service"

- name: Install the newest version of package "python3-pymysql"
  ansible.builtin.apt:
    name: python3-pymysql
    state: present

- name: MySQL database
  community.mysql.mysql_db:
    name: "{{ mysql_database }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock    

- name: MySQL user Agama
  community.mysql.mysql_user:
    name: "{{ mysql_user }}"
    password: "{{ mysql_password }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    host: "%"
    priv: "{{ mysql_database }}.*:ALL"

# - name: MySQL user Exporter
#   community.mysql.mysql_user:
#     name: "{{ mysql_exporter_user }}"
#     password: "{{ mysql_exporter_password }}"
#     login_unix_socket: /var/run/mysqld/mysqld.sock
#     host: "%"
#     priv: "{{ mysql_database }}.*:SUPER"
#     state: present
