- name: Restart nginx
  service:
    name: nginx
    state: restarted
  listen: "restart nginx"

- name: Reload systemd
  shell: "systemctl daemon-reload"

- name: Restart Nginx exporter
  service:
    name: prometheus-nginx-exporter
    state: restarted
  listen: "Restart Nginx exporter"
