- name: Daemon reload
  ansible.builtin.systemd:
    daemon_reload: yes

  - name: Restart mysql-exporter
    service:
      name: prometheus-mysqld-exporter
      state: restarted
    listen: "restart mysql-exporter service"
