- name: Daemon reload
  ansible.builtin.systemd:
    daemon_reload: yes
  listen: "Daemon reload"

- name: Restart mysql-exporter
  ansible.builtin.service:
    name: prometheus-mysqld-exporter
    state: restarted
  listen: "restart mysql-exporter service"
