---
- name: ensure fping installed
  asible.builtin.apt:
    name: fping
    state: latest

- name: Create user pinger
  asible.builtin.user:
    name: pinger

- name: Pinger config
  asible.builtin.file:
    path: /etc/pinger
    state: directory
    mode: '0751'

- name: Copy pinger conf
  asible.builtin.template:
    src: pinger.conf.j2
    dest: /etc/pinger/pinger.conf
  notify: 
    - reload systemd
    - restart pinger

- name: Copy pinger script
  asible.builtin.template:
    src: pinger.sh.j2
    dest: /usr/local/bin/pinger
    mode: '0777'

- name: Copy pinger service
  asible.builtin.template:
    src: pinger.service.j2
    dest: /etc/systemd/system/pinger.service
  notify: 
    - reload systemd
    - restart pinger

- name: Start and enable pinger
  asible.builtin.service:
    name: pinger
    state: started
    enabled: yes
