---
- name: Restart influxdb
  ansible.builtin.service:
    name: influxdb
    state: restarted
    enabled: yes
  listen: "restart telegraf"

- name: restarted telegraf
  service:
    name: telegraf
    state: restarted
    enabled: yes
  listen: "restart telegraf"