- name: install prometheus
  ansible.builtin.apt:
    name: prometheus

- name: start prometheus
  ansible.builtin.service:
    name: prometheus
    state: started
    enabled: yes

- name: copy confs
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - { src: "prom.yml.j2", dest: "/etc/prometheus/prometheus.yml" }
    - { src: "prometheus.j2", dest: "/etc/systemd/system/prometheus.service" }
  notify: 
    - reload daemon
    - restart prometheus
    - restart nginx

- name: execute handlers
  meta: flush_handlers
