- name: Install the newest version of Prometheus
  ansible.builtin.apt:
    name: prometheus
    state: present

- name: Copy file prom.yml to /etc/prometheus/prometheus.yml
  ansible.builtin.template:
    src: prom.yml.j2
    dest: /etc/prometheus/prometheus.yml
  notify: "prometheus service reload"

- name: Copy file prometheus.j2 to /etc/default/prometheus
  ansible.builtin.template:
    src: prometheus.j2
    dest: /etc/default/prometheus
  notify: "prometheus service reload"

- name: start Prometheus service
  ansible.builtin.service:
    name: prometheus
    state: started
    enabled: true

- name: Install the newest version of package "nginx"
  ansible.builtin.apt:
    name: nginx
    state: present

- name: Copy files/default to /etc/nginx/sites-enabled/default on remote virtual machine
  ansible.builtin.template:
    src: templates/default.j2
    dest: /etc/nginx/sites-enabled/default
  notify: "restart nginx service"

- name: start nginx service
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true
