- name: ensure docker is installed
  ansible.builtin.apt:
    name:
      - docker.io
      - python3-docker
    state: latest

- name: docker enabled
  ansible.builtin.service:
    name: docker
    state: started
    enabled: yes
