- name: reload daemon
  shell: "systemctl daemon-reload"

- name: restart prometheus
  asible.builtin.service:
    name: prometheus
    state: restarted
    enabled: yes

- name: restart nginx
  ansible.builtin.service:
    name: nginx
    state: restarted
    enabled: yes
