- name: Install bind
  ansible.builtin.apt:
    name: 
      - bind9
      - python3-dnspython 
    state: latest

- name: Enable Bind9
  ansible.builtin.service:
    name: bind9
    state: started
    enabled: yes

- name: copy confs
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - { src: "named.conf.options.j2", dest: "/etc/bind/named.conf.options" }
    - { src: "named.conf.local.j2", dest: "/etc/bind/named.conf.local" }
    - { src: "named.conf.j2", dest: "/etc/bind/named.conf"}
  no_log: true
  notify: 
    - restart bind9
    - reload rndc

- name: copy main zone and reverse zone in to the primary dns servers
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    force: no
  loop: 
    - { src: "zone.j2", dest: "/var/cache/bind/db.cybera.mk" }
    - { src: "sec_zone.j2", dest: "/var/cache/bind/db.reverse" }
  when: inventory_hostname in groups['dns_primary']
  notify: reload rndc 
  no_log: true

- name: Execute handlers preemptively
  meta: flush_handlers

- name: Set A records
  community.general.nsupdate:
    key_name: "{{ dns_update_key_name }}"
    key_algorithm: "hmac-sha256"
    key_secret: "{{ dns_update_key }}"
    server: "localhost"
    zone: "{{ domain_name }}"
    record: "{{ item.key }}"
    type: "A"
    value: "{{ item.value }}"
  loop: "{{ dns_a_records | dict2items }}"
  when: inventory_hostname in groups['dns_primary']
  no_log: true

- name: Set CNAME 
  community.general.nsupdate:
    key_name: "{{ dns_update_key_name }}"
    key_algorithm: "hmac-sha256"
    key_secret: "{{ dns_update_key }}"
    server: "localhost"
    zone: "{{ domain_name }}"
    record: "{{ item.key }}"
    type: "CNAME"
    value: "{{ item.value }}"
  loop: "{{ dns_cname_records | dict2items }}"
  when: inventory_hostname in groups['dns_primary']
  no_log: true
