#- name: Ansible ping module
#  ansible.builtin.ping:

- name: Update APT cache
  ansible.builtin.apt:
    cache_valid_time: 86400

#- name: Add the user 'johnd' with a specific uid and a primary group of 'admin' for Juri
#  ansible.builtin.user:
#    name: juri
#    comment: Juri Hudolejev
#    group: admin

#- name: Set authorized keys taken from url for Juri
#  ansible.posix.authorized_key:
#    user: juri
#    state: present
#    key: https://github.com/hudolejev.keys

#- name: Add the user 'johnd' with a specific uid and a primary group of 'admin' for Roman
#  ansible.builtin.user:
#    name: roman 
#    comment: Roman Kuchin
#    group: admin

#- name: Set authorized keys taken from url for Roman
#  ansible.posix.authorized_key:
#    user: roman
#    state: present
#    key: https://github.com/romankuchin.keys

- name: Install Prometheus Node Exporters            
  ansible.builtin.apt:
    name: prometheus-node-exporter
    state: present

- name: Copy file with owner and permission of resolv.conf for bind9 service
  ansible.builtin.template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf

- name: start prometheus-node-exporter service
  ansible.builtin.service:
    name: prometheus-node-exporter
    state: started
    enabled: true
