#- name: Ansible ping module
#  ansible.builtin.ping:

- name: Update APT cache
  ansible.builtin.apt:
    cache_valid_time: 86400

- name: Install ca-certificates
  ansible.builtin.apt:
    name: ca-certificates=20230311ubuntu0.20.04.1
    state: present

#- name: Add the user 'johnd' with a specific uid and a primary group of 'admin' for Juri
#  ansible.builtin.user:
#    name: juri
#    comment: Juri Hudolejev
#    group: admin

#- name: Set authorized keys taken from url for Juri
#  ansible.posix.authorized_key:
#    user: juri
#    state: present
#    key: https://github.com/hudolejev.keys

#- name: Add the user 'johnd' with a specific uid and a primary group of 'admin' for Roman
#  ansible.builtin.user:
#    name: roman 
#    comment: Roman Kuchin
#    group: admin

#- name: Set authorized keys taken from url for Roman
#  ansible.posix.authorized_key:
#    user: roman
#    state: present
#    key: https://github.com/romankuchin.keys

- name: Install Prometheus Node Exporters            
  ansible.builtin.apt:
    name: prometheus-node-exporter
    state: present

- name: start prometheus-node-exporter service
  ansible.builtin.service:
    name: prometheus-node-exporter
    state: started
    enabled: true

- name: backup user
  ansible.builtin.user:
    name: backup
    create_home: yes
    move_home: yes
    home: /home/backup
    generate_ssh_key: yes
    ssh_key_file: /home/backup/.ssh/id_rsa

- name: copy known hosts
  ansible.builtin.template:
    src: known_hosts.j2
    dest: /home/backup/.ssh/known_hosts
    owner: backup
    group: backup
    mode: '0774'

- name: restore directory
  ansible.builtin.file:
    path: /home/backup/restore
    state: directory
    owner: backup
    mode: '0774'

- name: ensure duplicity is installed
  ansible.builtin.apt:
    name: duplicity
    state: latest
